import type { AgentRole } from "@game-studio/types";

/**
 * Delegation rules from .claude/docs/agent-coordination-map.md
 * Maps which agents can delegate to which other agents.
 */
export const delegationMap: Record<AgentRole, AgentRole[]> = {
  "creative-director": [
    "game-designer",
    "art-director",
    "audio-director",
    "narrative-director",
  ],
  "technical-director": [
    "lead-programmer",
    "devops-engineer",
    "performance-analyst",
    "technical-artist",
  ],
  producer: [
    "creative-director",
    "technical-director",
    "game-designer",
    "lead-programmer",
    "art-director",
    "audio-director",
    "narrative-director",
    "qa-lead",
    "release-manager",
    "prototyper",
  ],
  "game-designer": ["systems-designer", "level-designer", "economy-designer"],
  "lead-programmer": [
    "gameplay-programmer",
    "engine-programmer",
    "ai-programmer",
    "network-programmer",
    "tools-programmer",
    "ui-programmer",
    "godot-specialist",
    "unity-specialist",
    "unreal-specialist",
  ],
  "art-director": ["technical-artist", "ux-designer"],
  "audio-director": ["sound-designer"],
  "narrative-director": ["writer", "world-builder"],
  "qa-lead": ["qa-tester"],
  "release-manager": ["devops-engineer", "qa-lead"],
  "localization-lead": ["writer", "ui-programmer"],
  prototyper: [],
  "security-engineer": ["network-programmer", "lead-programmer"],
  "accessibility-specialist": ["ux-designer", "ui-programmer", "qa-tester"],
  "godot-specialist": ["godot-gdscript-specialist", "godot-shader-specialist", "godot-gdextension-specialist"],
  "unity-specialist": [
    "unity-dots-specialist",
    "unity-shader-specialist",
    "unity-addressables-specialist",
    "unity-ui-specialist",
  ],
  "unreal-specialist": [
    "ue-gas-specialist",
    "ue-blueprint-specialist",
    "ue-replication-specialist",
    "ue-umg-specialist",
  ],
  "live-ops-designer": ["economy-designer", "community-manager", "analytics-engineer"],
  "community-manager": [],
  // Specialists - no delegation
  "systems-designer": [],
  "level-designer": [],
  "economy-designer": [],
  "ux-designer": [],
  "gameplay-programmer": [],
  "engine-programmer": [],
  "ai-programmer": [],
  "network-programmer": [],
  "tools-programmer": [],
  "ui-programmer": [],
  "technical-artist": [],
  "sound-designer": [],
  writer: [],
  "world-builder": [],
  "qa-tester": [],
  "performance-analyst": [],
  "devops-engineer": [],
  "analytics-engineer": [],
  "godot-gdscript-specialist": [],
  "godot-shader-specialist": [],
  "godot-gdextension-specialist": [],
  "unity-dots-specialist": [],
  "unity-shader-specialist": [],
  "unity-addressables-specialist": [],
  "unity-ui-specialist": [],
  "ue-gas-specialist": [],
  "ue-blueprint-specialist": [],
  "ue-replication-specialist": [],
  "ue-umg-specialist": [],
};
