import type { AgentDefinition, AgentRole } from "@game-studio/types";

export const unityAgents: Partial<Record<AgentRole, AgentDefinition>> = {
  "unity-specialist": {
    name: "unity-specialist",
    description: "Unity lead: MonoBehaviour/DOTS, Addressables, URP/HDRP.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "UnityCLI"],
    maxTurns: 35,
    skills: ["dev-story", "code-review", "setup-unity-project", "implement-unity-mono", "implement-unity-dots", "implement-unity-urp", "automated-unity-playtest", "unity-cli-ops"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "unity-dots-specialist": {
    name: "unity-dots-specialist",
    description: "DOTS/ECS: Jobs, Burst compiler, hybrid renderer.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "UnityCLI"],
    maxTurns: 30,
    skills: ["dev-story", "setup-unity-project", "implement-unity-mono", "implement-unity-dots", "implement-unity-urp", "automated-unity-playtest", "unity-cli-ops"],
    memory: "session",
    reportsTo: ["unity-specialist"],
  },
  "unity-shader-specialist": {
    name: "unity-shader-specialist",
    description: "Shaders: Shader Graph, VFX Graph, SRP customization.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "UnityCLI"],
    maxTurns: 25,
    skills: ["setup-unity-project", "implement-unity-mono", "implement-unity-dots", "implement-unity-urp", "automated-unity-playtest", "unity-cli-ops"],
    memory: "session",
    reportsTo: ["unity-specialist", "technical-artist"],
  },
  "unity-addressables-specialist": {
    name: "unity-addressables-specialist",
    description: "Assets: async loading, bundles, memory management, CDN integration.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "UnityCLI"],
    maxTurns: 25,
    skills: ["setup-unity-project", "implement-unity-mono", "implement-unity-dots", "implement-unity-urp", "automated-unity-playtest", "unity-cli-ops"],
    memory: "session",
    reportsTo: ["unity-specialist"],
  },
  "unity-ui-specialist": {
    name: "unity-ui-specialist",
    description: "UI: UI Toolkit, UGUI, UXML/USS, data binding.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "UnityCLI"],
    maxTurns: 25,
    skills: ["ux-design", "dev-story", "setup-unity-project", "implement-unity-mono", "implement-unity-dots", "implement-unity-urp", "automated-unity-playtest", "unity-cli-ops"],
    memory: "session",
    reportsTo: ["unity-specialist", "ui-programmer"],
  },
};
