import type { AgentDefinition, AgentRole } from "@game-studio/types";

export const godotAgents: Partial<Record<AgentRole, AgentDefinition>> = {
  "godot-scaffolder": {
    name: "godot-scaffolder",
    description: "Creates a complete Godot 4 project from scratch — project.godot, directory structure, autoloads, input map, boot scene, and main menu. Works with the Godot MCP or via file I/O.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "Task"],
    maxTurns: 25,
    skills: ["setup-godot-project"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "godot-specialist": {
    name: "godot-specialist",
    description: "Godot 4 lead: GDScript, node/scene, signals, resources.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "Task", "GodotCLI"],
    maxTurns: 35,
    skills: ["dev-story", "code-review", "compose-scene", "setup-godot-project", "implement-player-controller", "automated-playtest", "export-godot-project", "run-godot-headless", "implement-game-state", "implement-tilemap", "implement-level", "implement-enemy", "implement-hud", "implement-save-system", "playtest-with-mcp", "godot-cli-ops"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "godot-gdscript-specialist": {
    name: "godot-gdscript-specialist",
    description: "GDScript: static typing, patterns, signals, performance.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "Task"],
    maxTurns: 30,
    skills: ["dev-story", "compose-scene", "implement-player-controller", "implement-game-state", "implement-tilemap", "implement-level", "implement-enemy", "implement-hud", "run-godot-headless"],
    memory: "session",
    reportsTo: ["godot-specialist"],
  },
  "godot-shader-specialist": {
    name: "godot-shader-specialist",
    description: "Godot shading language, visual shaders, VFX.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "Task"],
    maxTurns: 25,
    skills: ["implement-shader-effect"],
    memory: "session",
    reportsTo: ["godot-specialist", "technical-artist"],
  },
  "godot-gdextension-specialist": {
    name: "godot-gdextension-specialist",
    description: "Native: C++/Rust bindings, GDExtension, build systems.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 30,
    skills: ["dev-story"],
    memory: "session",
    reportsTo: ["godot-specialist"],
    experimental: true,
  },
};
