import type { AgentDefinition, AgentRole } from "@game-studio/types";

export const unrealAgents: Partial<Record<AgentRole, AgentDefinition>> = {
  "unreal-specialist": {
    name: "unreal-specialist",
    description: "UE5 lead: Blueprint/C++, GAS overview, UE subsystems.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "UnrealCLI"],
    maxTurns: 35,
    skills: ["dev-story", "code-review", "setup-unreal-project", "implement-ue-blueprint", "implement-ue-gas", "implement-ue-replication", "automated-ue-playtest", "unreal-cli-ops"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "ue-gas-specialist": {
    name: "ue-gas-specialist",
    description: "GAS: abilities, effects, attributes, tags, prediction.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "UnrealCLI"],
    maxTurns: 30,
    skills: ["dev-story", "setup-unreal-project", "implement-ue-blueprint", "implement-ue-gas", "implement-ue-replication", "automated-ue-playtest", "unreal-cli-ops"],
    memory: "session",
    reportsTo: ["unreal-specialist"],
  },
  "ue-blueprint-specialist": {
    name: "ue-blueprint-specialist",
    description: "Blueprint: BP/C++ boundary, graph standards, optimization.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "UnrealCLI"],
    maxTurns: 25,
    skills: ["dev-story", "setup-unreal-project", "implement-ue-blueprint", "implement-ue-gas", "implement-ue-replication", "automated-ue-playtest", "unreal-cli-ops"],
    memory: "session",
    reportsTo: ["unreal-specialist"],
  },
  "ue-replication-specialist": {
    name: "ue-replication-specialist",
    description: "Networking: replication, RPCs, prediction, bandwidth optimization.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "UnrealCLI"],
    maxTurns: 30,
    skills: ["dev-story", "setup-unreal-project", "implement-ue-blueprint", "implement-ue-gas", "implement-ue-replication", "automated-ue-playtest", "unreal-cli-ops"],
    memory: "session",
    reportsTo: ["unreal-specialist", "network-programmer"],
  },
  "ue-umg-specialist": {
    name: "ue-umg-specialist",
    description: "UI: UMG, CommonUI, widget hierarchy, data binding.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "UnrealCLI"],
    maxTurns: 25,
    skills: ["ux-design", "dev-story", "setup-unreal-project", "implement-ue-blueprint", "implement-ue-gas", "implement-ue-replication", "automated-ue-playtest", "unreal-cli-ops"],
    memory: "session",
    reportsTo: ["unreal-specialist", "ui-programmer"],
  },
};
