import type { AgentDefinition, AgentRole } from "@game-studio/types";

export const unrealAgents: Partial<Record<AgentRole, AgentDefinition>> = {
  "unreal-specialist": {
    name: "unreal-specialist",
    description: "UE5 lead: Blueprint/C++, GAS overview, UE subsystems.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 35,
    skills: ["dev-story", "code-review"],
    memory: "session",
    reportsTo: ["lead-programmer"],
    experimental: true,
  },
  "ue-gas-specialist": {
    name: "ue-gas-specialist",
    description: "GAS: abilities, effects, attributes, tags, prediction.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 30,
    skills: ["dev-story"],
    memory: "session",
    reportsTo: ["unreal-specialist"],
    experimental: true,
  },
  "ue-blueprint-specialist": {
    name: "ue-blueprint-specialist",
    description: "Blueprint: BP/C++ boundary, graph standards, optimization.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 25,
    skills: ["dev-story"],
    memory: "session",
    reportsTo: ["unreal-specialist"],
    experimental: true,
  },
  "ue-replication-specialist": {
    name: "ue-replication-specialist",
    description: "Networking: replication, RPCs, prediction, bandwidth optimization.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 30,
    skills: ["dev-story"],
    memory: "session",
    reportsTo: ["unreal-specialist", "network-programmer"],
    experimental: true,
  },
  "ue-umg-specialist": {
    name: "ue-umg-specialist",
    description: "UI: UMG, CommonUI, widget hierarchy, data binding.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 25,
    skills: ["ux-design", "dev-story"],
    memory: "session",
    reportsTo: ["unreal-specialist", "ui-programmer"],
    experimental: true,
  },
};
