import type { AgentDefinition, AgentRole } from "@game-studio/types";

export const specialistAgents: Partial<Record<AgentRole, AgentDefinition>> = {
  "systems-designer": {
    name: "systems-designer",
    description: "Systems mechanics, loops, and balance.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 30,
    skills: ["design-system", "quick-design", "balance-check"],
    memory: "session",
    reportsTo: ["game-designer"],
  },
  "level-designer": {
    name: "level-designer",
    description: "Level layout, encounter design, pacing.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 30,
    skills: ["design-system", "quick-design"],
    memory: "session",
    reportsTo: ["game-designer"],
  },
  "economy-designer": {
    name: "economy-designer",
    description: "Economy modeling, progression curves, reward systems.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 25,
    skills: ["balance-check", "design-system"],
    memory: "session",
    reportsTo: ["game-designer"],
  },
  "ux-designer": {
    name: "ux-designer",
    description: "User experience, interaction patterns, accessibility.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Task"],
    maxTurns: 25,
    skills: ["ux-design", "ux-review"],
    memory: "session",
    reportsTo: ["art-director"],
  },
  "gameplay-programmer": {
    name: "gameplay-programmer",
    description: "Gameplay mechanics, player controls, game rules.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash", "Task"],
    maxTurns: 40,
    skills: ["dev-story", "story-done", "code-review", "implement-player-controller", "compose-scene", "implement-game-state", "implement-enemy", "implement-hud", "implement-level"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "engine-programmer": {
    name: "engine-programmer",
    description: "Engine-level systems, rendering, physics.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 40,
    skills: ["dev-story", "code-review"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "ai-programmer": {
    name: "ai-programmer",
    description: "AI behavior, decision trees, pathfinding.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 35,
    skills: ["dev-story", "code-review"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "network-programmer": {
    name: "network-programmer",
    description: "Networking, replication, online features.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 35,
    skills: ["dev-story", "code-review", "implement-multiplayer"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "tools-programmer": {
    name: "tools-programmer",
    description: "Editor tools, pipeline utilities, automation.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 30,
    skills: ["dev-story"],
    memory: "session",
    reportsTo: ["lead-programmer"],
    experimental: true,
  },
  "ui-programmer": {
    name: "ui-programmer",
    description: "UI implementation, HUD, menus.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 30,
    skills: ["dev-story", "ux-design", "implement-hud"],
    memory: "session",
    reportsTo: ["lead-programmer"],
  },
  "technical-artist": {
    name: "technical-artist",
    description: "Shader development, VFX, pipeline integration.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 30,
    skills: ["implement-shader-effect", "generate-audio-asset"],
    memory: "session",
    reportsTo: ["art-director", "technical-director"],
  },
  "sound-designer": {
    name: "sound-designer",
    description: "Sound effects, ambient audio, audio implementation.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 25,
    skills: ["generate-audio-asset"],
    memory: "session",
    reportsTo: ["audio-director"],
  },
  writer: {
    name: "writer",
    description: "Dialogue, lore, item descriptions. Writes narrative content that adheres to the GDD tone.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 25,
    skills: ["write-dialogue", "write-lore", "localize"],
    memory: "session",
    reportsTo: ["narrative-director"],
  },
  "world-builder": {
    name: "world-builder",
    description: "World lore, setting, environmental storytelling.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 30,
    skills: ["write-lore", "localize"],
    memory: "session",
    reportsTo: ["narrative-director"],
  },
  "qa-tester": {
    name: "qa-tester",
    description: "Test execution, bug reporting, regression testing, automated playtest.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Glob", "Grep", "Bash", "Task"],
    maxTurns: 25,
    skills: ["automated-playtest", "bug-report", "qa-plan", "smoke-check", "regression-suite"],
    memory: "session",
    reportsTo: ["qa-lead"],
  },
  "performance-analyst": {
    name: "performance-analyst",
    description: "Performance profiling, bottleneck identification, optimization.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 30,
    skills: ["perf-profile", "smoke-check"],
    memory: "session",
    reportsTo: ["technical-director"],
  },
  "devops-engineer": {
    name: "devops-engineer",
    description: "CI/CD, build automation, deployment pipelines.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 25,
    skills: ["test-setup", "release-checklist", "export-godot-project", "automated-playtest", "run-godot-headless"],
    memory: "session",
    reportsTo: ["technical-director", "release-manager"],
  },
  "analytics-engineer": {
    name: "analytics-engineer",
    description: "Metrics tracking, data pipelines, analytics dashboards.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 25,
    skills: ["perf-profile"],
    memory: "session",
    reportsTo: ["producer"],
  },
  "security-engineer": {
    name: "security-engineer",
    description: "Security auditing, anti-cheat, vulnerability assessment.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 30,
    skills: ["security-audit"],
    memory: "session",
    reportsTo: ["technical-director"],
    experimental: true,
  },
  prototyper: {
    name: "prototyper",
    description: "Rapid throwaway prototypes, concept validation.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    maxTurns: 50,
    skills: ["prototype"],
    memory: "session",
    reportsTo: ["producer"],
    experimental: true,
  },
  "accessibility-specialist": {
    name: "accessibility-specialist",
    description: "WCAG compliance, accessibility features, inclusive design.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 25,
    skills: ["ux-review"],
    memory: "session",
    reportsTo: ["art-director", "qa-lead"],
  },
  "live-ops-designer": {
    name: "live-ops-designer",
    description: "Live events, seasons, battle passes, retention.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 30,
    skills: [],
    memory: "session",
    reportsTo: ["producer"],
  },
  "community-manager": {
    name: "community-manager",
    description: "Player communication, patch notes, community engagement.",
    tier: 3,
    model: "sonnet",
    tools: ["Read", "Write", "Edit", "Glob", "Grep"],
    maxTurns: 20,
    skills: ["changelog", "patch-notes"],
    memory: "project",
    reportsTo: ["producer"],
  },
};
