import type {
  BuildPlatform,
  BuildValidationResult,
  EngineAdapter,
  ExportResult,
  ProjectEngine,
  TestResult,
  ToolDefinition,
} from "@game-studio/types";
import fsPromises from "fs/promises";
import { join, relative } from "path";

/**
 * UnityEngineAdapter — EngineAdapter contract for Unity projects.
 *
 * This is a stub implementation that scaffolds a minimal project structure
 * and returns placeholder results for build, test, and export operations.
 */
export class UnityEngineAdapter implements EngineAdapter {
  readonly engine: ProjectEngine = "unity";

  getScaffolder(): "unity-specialist" {
    return "unity-specialist";
  }

  getSpecialist(): "unity-specialist" {
    return "unity-specialist";
  }

  getTools(): ToolDefinition[] {
    return [
      {
        name: "UnityCLI",
        description:
          "Operate a Unity project. create-project scaffolds a minimal project; run-tests invokes the test runner; build produces an artifact for windows, macos, linux, or web.",
        input_schema: {
          type: "object",
          properties: {
            projectPath: { type: "string", description: "Absolute path to the Unity project root" },
            command: {
              type: "string",
              enum: ["create-project", "run-tests", "build"],
              description: "UnityCLI command",
            },
            name: { type: "string", description: "Project name (used by create-project)" },
            platform: {
              type: "string",
              enum: ["windows", "macos", "linux", "web"],
              description: "Build target (used by build)",
            },
          },
          required: ["projectPath", "command"],
        },
      },
    ];
  }

  getInstructions(): string {
    return "";
  }

  async scaffold(projectPath: string, name: string): Promise<void> {
    await fsPromises.mkdir(join(projectPath, "Assets", "Scripts"), { recursive: true });
    await fsPromises.mkdir(join(projectPath, "Assets", "Scenes"), { recursive: true });
    await fsPromises.mkdir(join(projectPath, "Assets", "Prefabs"), { recursive: true });
    await fsPromises.mkdir(join(projectPath, "Assets", "Resources"), { recursive: true });
    await fsPromises.mkdir(join(projectPath, "ProjectSettings"), { recursive: true });
    await fsPromises.mkdir(join(projectPath, "Packages"), { recursive: true });

    await fsPromises.writeFile(
      join(projectPath, "README.md"),
      `# ${name}\n\nUnity project generated by Game Studio Control Plane.\n\n## Layout\n\n- Assets/Scripts — C# scripts and DOTS systems\n- Assets/Scenes — scene files\n- Assets/Prefabs — reusable prefabs\n- Assets/Resources — runtime-loaded assets\n- ProjectSettings/ — Unity project settings\n- Packages/ — package manifest\n`,
    );

    await fsPromises.writeFile(
      join(projectPath, "Packages", "manifest.json"),
      JSON.stringify(
        {
          dependencies: {
            "com.unity.modules.core": "1.0.0",
            "com.unity.modules.physics": "1.0.0",
            "com.unity.modules.physics2d": "1.0.0",
            "com.unity.modules.ui": "1.0.0",
            "com.unity.render-pipelines.universal": "14.0.0",
            "com.unity.entities": "1.0.0",
            "com.unity.test-framework": "1.3.0",
            "com.unity.addressables": "1.21.0",
          },
        },
        null,
        2,
      ),
    );
  }

  async validateBuild(projectPath: string): Promise<BuildValidationResult> {
    return { ok: true, errors: [] };
  }

  async runTests(projectPath: string): Promise<TestResult> {
    return { ok: true, output: "Unity tests stub — no test runner executed." };
  }

  async export(
    projectPath: string,
    platform: BuildPlatform,
    options?: {
      preset?: string;
      projectId?: string;
      version?: string;
      bumpVersion?: boolean;
    },
  ): Promise<ExportResult> {
    const supported: Partial<Record<BuildPlatform, true>> = {
      windows: true,
      macos: true,
      linux: true,
      web: true,
    };
    if (!supported[platform]) {
      throw new Error(`Unity export does not support platform "${platform}". Supported: windows, macos, linux, web.`);
    }

    const projectId = options?.projectId ?? "project";
    const version = options?.version ?? "0.1.0";
    const artifactName = `${projectId}-${platform}-v${version}-${Date.now()}.zip`;
    const buildsDir = join(projectPath, "builds");
    await fsPromises.mkdir(buildsDir, { recursive: true });
    const artifactAbs = join(buildsDir, artifactName);
    await fsPromises.writeFile(artifactAbs, "Unity build artifact placeholder");

    return { artifactPath: relative(projectPath, artifactAbs) };
  }

  getQAChain(): string[] {
    return ["smoke", "regression"];
  }
}
