/**
 * UnrealEngineAdapter — EngineAdapter contract implementation for Unreal Engine 5.
 *
 * Provides scaffolding, build/test stubs, and export paths for the Unreal
 * project layout. The adapter is intentionally lightweight until UE5 build
 * automation is wired in later.
 */

import type {
  BuildPlatform,
  BuildValidationResult,
  EngineAdapter,
  ExportResult,
  ProjectEngine,
  TestResult,
  ToolDefinition,
} from "@game-studio/types";
import fsPromises from "fs/promises";
import { join, relative } from "path";

const SUPPORTED_PLATFORMS: Record<string, true> = {
  windows: true,
  macos: true,
  linux: true,
};

export class UnrealEngineAdapter implements EngineAdapter {
  readonly engine: ProjectEngine = "unreal";

  getScaffolder(): "unreal-specialist" {
    return "unreal-specialist";
  }

  getSpecialist(): "unreal-specialist" {
    return "unreal-specialist";
  }

  getTools(): ToolDefinition[] {
    return [
      {
        name: "UnrealCLI",
        description:
          "Operate an Unreal Engine 5 project. " +
          "create-project scaffolds a new UE5 project; run-tests executes the project's test suite; " +
          "build compiles the project for a target platform (windows, macos, linux).",
        input_schema: {
          type: "object",
          properties: {
            projectPath: { type: "string", description: "Absolute path to the Unreal project root" },
            command: {
              type: "string",
              enum: ["create-project", "run-tests", "build"],
              description: "UnrealCLI command to run",
            },
            name: { type: "string", description: "Project name (used only by create-project)" },
            platform: {
              type: "string",
              enum: ["windows", "macos", "linux"],
              description: "Target platform (used only by build)",
            },
          },
          required: ["projectPath", "command"],
        },
      },
    ];
  }

  getInstructions(): string {
    return [
      "You are working in an Unreal Engine 5 project.",
      "Use Blueprint/C++ best practices: follow naming conventions, keep graphs readable,",
      "prefer data-driven design for GAS attributes and effects, and replicate only what is necessary.",
    ].join(" ");
  }

  async scaffold(projectPath: string, name: string): Promise<void> {
    await fsPromises.mkdir(projectPath, { recursive: true });

    const folders = ["Content", "Source", "Config", "Plugins", "Build"];
    for (const folder of folders) {
      await fsPromises.mkdir(join(projectPath, folder), { recursive: true });
    }

    const readmePath = join(projectPath, "README.md");
    const readme = [
      `# ${name}`,
      "",
      "Unreal Engine 5 project generated by the Game Studio Control Plane.",
      "",
      "## Folders",
      "",
      "- `Content/` — assets, blueprints, levels, materials",
      "- `Source/` — C++ source code",
      "- `Config/` — engine and project configuration files",
      "- `Plugins/` — project plugins",
      "- `Build/` — build artifacts and cooked data",
      "",
      "## Next steps",
      "",
      "1. Open the `.uproject` file in Unreal Editor.",
      "2. Generate Visual Studio//Xcode project files from the editor.",
      "3. Use the `UnrealCLI` tool for automated create-project, build, and run-tests.",
      "",
    ].join("\n");
    await fsPromises.writeFile(readmePath, readme, "utf-8");

    const uprojectPath = join(projectPath, `${name}.uproject`);
    const uproject = {
      FileVersion: 3,
      EngineAssociation: "5.4",
      Category: "",
      Description: "",
      Modules: [
        {
          Name: name,
          Type: "Runtime",
          LoadingPhase: "Default",
        },
      ],
      Plugins: [],
    };
    await fsPromises.writeFile(uprojectPath, JSON.stringify(uproject, null, 2), "utf-8");
  }

  async validateBuild(_projectPath: string): Promise<BuildValidationResult> {
    return { ok: true, errors: [] };
  }

  async runTests(_projectPath: string): Promise<TestResult> {
    return { ok: true, output: "Unreal tests stub — no test runner configured yet." };
  }

  async export(
    projectPath: string,
    platform: BuildPlatform,
    options?: {
      preset?: string;
      projectId?: string;
      version?: string;
      bumpVersion?: boolean;
    },
  ): Promise<ExportResult> {
    if (!SUPPORTED_PLATFORMS[platform]) {
      throw new Error(`Unsupported Unreal export platform: ${platform}. Supported platforms: windows, macos, linux.`);
    }

    const projectId = options?.projectId ?? "project";
    const version = options?.version ?? "0.1.0";
    const artifactName = `${projectId}-${platform}-v${version}-${Date.now()}.zip`;
    const buildsDir = join(projectPath, "builds");
    await fsPromises.mkdir(buildsDir, { recursive: true });
    const artifactAbs = join(buildsDir, artifactName);
    await fsPromises.writeFile(artifactAbs, "Unreal build stub", "utf-8");

    return { artifactPath: relative(projectPath, artifactAbs) };
  }

  getQAChain(): string[] {
    return ["smoke", "regression"];
  }
}
