import { Router } from "express";
import type { Request, Response } from "express";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import path from "node:path";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import { watch } from "node:fs";
import { fileURLToPath } from "node:url";
import { readData, writeData, updateData, broadcastEvent } from "../services/data-store.js";
import { logger } from "../utils/logger.js";
import { resolveProjectWorkspace } from "../utils/workspace.js";
import type {
  AssetsData,
  GameAsset,
  ArtBibleConfig,
  CreateAssetRequest,
  UpdateAssetRequest,
  AssetGenerationMeta,
  Project,
} from "@game-studio/types";
import type { WSEvent } from "@game-studio/types";
import { loadConfig, resolvePipelinePython, SUBPROCESS_MAX_BUFFER } from "../config.js";

const execFileAsync = promisify(execFile);

const PYTHON_BIN = resolvePipelinePython();

/** Known asset file extensions mapped to types */
const EXT_TO_TYPE: Record<string, GameAsset["type"]> = {
  ".png": "2d",
  ".jpg": "2d",
  ".jpeg": "2d",
  ".webp": "2d",
  ".gif": "2d",
  ".bmp": "2d",
  ".fbx": "3d",
  ".obj": "3d",
  ".gltf": "3d",
  ".glb": "3d",
  ".blend": "3d",
  ".mp3": "audio",
  ".wav": "audio",
  ".ogg": "audio",
  ".flac": "audio",
  ".ttf": "texture",
  ".otf": "texture",
  ".font": "texture",
};

/** Infer asset type from filename/extension */
function inferType(filename: string): GameAsset["type"] {
  const ext = path.extname(filename).toLowerCase();
  return EXT_TO_TYPE[ext] ?? "texture";
}

/** Infer category from filename keywords */
function inferCategory(filename: string): GameAsset["category"] {
  const lower = filename.toLowerCase();
  if (/char|player|hero|enemy|npc|mob|unit/i.test(lower)) return "character";
  if (/weapon|sword|gun|bow|axe|staff|dagger|shield/i.test(lower)) return "weapon";
  if (/env|bg_|background|tile|terrain|map|level|world|ground/i.test(lower)) return "env";
  if (/ui_|hud|icon|button|panel|frame|menu|cursor/i.test(lower)) return "ui";
  if (/sfx|sound_|hit_|jump_|step_|click/i.test(lower)) return "sfx";
  if (/music|bgm|theme|song|loop/i.test(lower)) return "music";
  if (/tex|texture|pattern|material/i.test(lower)) return "tex";
  return "prop";
}

interface GenerateAssetRequest {
  prompt: string;
  name: string;
  type?: "2d" | "3d" | "vfx" | "audio" | "texture";
  category?: "prop" | "character" | "env" | "weapon" | "ui" | "tex" | "sfx" | "music";
  width?: number;
  height?: number;
  steps?: number;
  seed?: number;
  removeBg?: boolean;
  negativePrompt?: string;
  model?: string;
  gridSize?: number;
  spriteSheet?: boolean;
  spriteCols?: number;
  spriteRows?: number;
  tags?: string[];
  presetsFile?: string;
  workspacePath?: string;
}

const DEFAULT_ASSETS: AssetsData = {
  assets: [],
  artBible: {
    baseTextureRes: 256,
    maxPolycount: 1500,
    enforcePalette: true,
    strictOrthographic: false,
    snapToGrid: true,
    gridSize: 8,
  },
};

// 10-L1: signed thumbnail URLs. The /:id/thumbnail route is exempt
// from auth (browsers can't send Authorization on <img src>), which
// means anyone who knows or guesses an asset id can fetch the
// thumbnail. Asset ids are UUIDs so guessing is impractical, but
// enumeration is a real concern if the list endpoint ever leaks to
// an unauthenticated consumer. Require an HMAC of the asset id signed
// with API_SECRET on every thumbnail request — generated by the list
// endpoint and embedded in the URL, verified in constant time.
function signThumbnailId(id: string): string {
  return crypto
    .createHmac("sha256", loadConfig().API_SECRET)
    .update(`thumbnail:${id}`)
    .digest("hex")
    .slice(0, 32);
}
function verifyThumbnailSignature(id: string, sig: string): boolean {
  const expected = signThumbnailId(id);
  if (expected.length !== sig.length) return false;
  return crypto.timingSafeEqual(Buffer.from(expected, "hex"), Buffer.from(sig, "hex"));
}

function manifestEntryToGameAsset(entry: Record<string, unknown>): GameAsset {
  // Validate the discriminator fields before casting — an unknown type or
  // category string would otherwise leak through as an un-castable value
  // and crash downstream code (e.g. `assets.filter(a => a.type === "2d")`).
  const VALID_TYPES: GameAsset["type"][] = ["3d", "2d", "vfx", "audio", "texture"];
  const VALID_CATEGORIES: GameAsset["category"][] = [
    "prop", "character", "env", "weapon", "ui", "tex", "sfx", "music",
  ];
  const type = VALID_TYPES.includes(entry.type as GameAsset["type"])
    ? (entry.type as GameAsset["type"])
    : "2d";
  const category = VALID_CATEGORIES.includes(entry.category as GameAsset["category"])
    ? (entry.category as GameAsset["category"])
    : "prop";

  const generatedWith: AssetGenerationMeta | undefined =
    entry.generatedWith && typeof entry.generatedWith === "object"
      ? (entry.generatedWith as AssetGenerationMeta)
      : undefined;

  return {
    id: typeof entry.id === "string" ? entry.id : "",
    filename: typeof entry.filename === "string" ? entry.filename : "unknown",
    type,
    category,
    sizeBytes: typeof entry.sizeBytes === "number" ? entry.sizeBytes : 0,
    tags: Array.isArray(entry.tags) ? (entry.tags as string[]) : [],
    createdAt: typeof entry.createdAt === "string" ? entry.createdAt : new Date().toISOString(),
    updatedAt: typeof entry.updatedAt === "string" ? entry.updatedAt : new Date().toISOString(),
    path: typeof entry.path === "string" ? entry.path : undefined,
    rawPath: typeof entry.rawPath === "string" ? entry.rawPath : undefined,
    thumbnailPath: typeof entry.thumbnailPath === "string" ? entry.thumbnailPath : undefined,
    generatedWith,
  };
}

/**
 * Build a GameAsset from a filesystem entry, merging with saved metadata overlay.
 */
function fileEntryToGameAsset(
  relPath: string,
  sizeBytes: number,
  stat: { ctime: Date; mtime: Date },
  overlay?: Partial<GameAsset>,
  fullPath?: string
): GameAsset {
  const filename = path.basename(relPath);
  // Use a hash of the full absolute path for the ID to avoid collisions
  // when relPath contains ".." or when truncated base64 collides
  const idSource = fullPath || relPath;
  const id = overlay?.id ?? `asset-${crypto.createHash("sha256").update(idSource).digest("hex").slice(0, 16)}`;
  return {
    id,
    filename: overlay?.filename ?? filename,
    type: overlay?.type ?? inferType(filename),
    category: overlay?.category ?? inferCategory(filename),
    sizeBytes,
    tags: overlay?.tags ?? [],
    createdAt: overlay?.createdAt ?? stat.ctime.toISOString(),
    updatedAt: overlay?.updatedAt ?? stat.mtime.toISOString(),
    path: relPath,
    thumbnailPath: overlay?.thumbnailPath ?? undefined,
    generatedWith: overlay?.generatedWith ?? undefined,
  };
}

/** Resolve project by ID from dashboard data */
async function getProjectById(projectId: string): Promise<Project | null> {
  try {
    const dashboard = await readData<{ projects: Project[] }>("dashboard.json");
    return dashboard.projects.find((p) => p.id === projectId) ?? null;
  } catch {
    return null;
  }
}

/** Resolve the assets directory for a project */
function resolveAssetsDir(workspaceDir: string, workspacePath?: string | null): string {
  if (!workspacePath) return path.join(workspaceDir, "assets");
  const projectDir = resolveProjectWorkspace(workspacePath);
  return path.join(projectDir, "assets");
}

/**
 * Scan a directory for asset files and return GameAsset list, merged with metadata overlay.
 */
async function scanAssetsDir(
  assetsDir: string,
  workspaceDir: string,
  overlayMap: Map<string, Partial<GameAsset>>
): Promise<GameAsset[]> {
  const results: GameAsset[] = [];

  let entries: { name: string; isDirectory: boolean; parentPath?: string }[] = [];
  try {
    const dirents = await fs.readdir(assetsDir, { withFileTypes: true, recursive: true });
    entries = dirents.map((d) => ({
      name: d.name,
      isDirectory: d.isDirectory(),
      parentPath: (d as unknown as { parentPath?: string; path?: string }).parentPath
        ?? (d as unknown as { path?: string }).path,
    }));
  } catch {
    // Directory doesn't exist or isn't readable — return empty
    return results;
  }

  for (const entry of entries) {
    if (entry.isDirectory) continue;
    const fullPath = path.join(entry.parentPath ?? assetsDir, entry.name);
    const relPath = path.relative(workspaceDir, fullPath);

    // Skip hidden/system files and non-asset files
    if (entry.name.startsWith(".") || entry.name.startsWith("_")) continue;
    const ext = path.extname(entry.name).toLowerCase();
    if (!ext || ext === ".json" || ext === ".md" || ext === ".txt" || ext === ".yaml" || ext === ".yml") continue;

    try {
      const stat = await fs.stat(fullPath);
      if (!stat.isFile()) continue;

      // Look up metadata overlay by relative path
      const overlay = overlayMap.get(relPath);
      const asset = fileEntryToGameAsset(relPath, stat.size, stat, overlay, fullPath);
      results.push(asset);
    } catch {
      // Skip unreadable files
    }
  }

  return results;
}

/** Active fs.watch watchers keyed by projectId. Capped via LRU eviction so a
 *  long-running API process that creates and deletes many projects doesn't
 *  leak watcher handles (and the OS file descriptors behind them). The cap
 *  is read from config so it can be tuned per deployment. */
const assetWatchers = new Map<string, ReturnType<typeof watch>>();

/**
 * Per-project debounce timer for asset watcher broadcasts. A single
 * editor save can fire 5-20 fs.watch events (open, write, write-end,
 * attribute change, rename, etc.) within milliseconds. Without
 * debouncing the WS broadcast every event, the studio hook processes
 * 20× the work and the LLM-side redraw handler is overwhelmed.
 *
 * 11-H3: 100ms window — long enough to coalesce a single save into
 * one broadcast, short enough to feel instant in the UI.
 */
const assetWatcherDebounceTimers = new Map<string, NodeJS.Timeout>();
const ASSET_WATCHER_DEBOUNCE_MS = 100;

/** Stop watching a project's assets directory */
export function unwatchProjectAssets(projectId: string): void {
  // 11-H3: also clear any pending debounce timer so it doesn't fire
  // after the project is gone (and so the Map doesn't accumulate
  // dead entries).
  const pendingTimer = assetWatcherDebounceTimers.get(projectId);
  if (pendingTimer) {
    clearTimeout(pendingTimer);
    assetWatcherDebounceTimers.delete(projectId);
  }
  const watcher = assetWatchers.get(projectId);
  if (watcher) {
    watcher.close();
    assetWatchers.delete(projectId);
    logger.info({ projectId }, "Stopped watching project assets");
  }
}

/** Start watching a project's assets directory for changes */
function watchProjectAssets(projectId: string, assetsDir: string): void {
  if (assetWatchers.has(projectId)) {
    // Touch the entry so the LRU eviction below considers this project
    // as the most-recently-used. Map.set on an existing key already
    // updates iteration order, but a delete+set makes the intent
    // explicit and matches the pattern used by the rate limiter above.
    const existing = assetWatchers.get(projectId)!;
    assetWatchers.delete(projectId);
    assetWatchers.set(projectId, existing);
    return;
  }

  // LRU: if we're at the cap, evict the oldest entry. Map iteration is
  // insertion order, so the first key is the least-recently-inserted.
  const watcherLimit = loadConfig().ASSET_WATCHER_LIMIT;
  if (assetWatchers.size >= watcherLimit) {
    const oldest = assetWatchers.keys().next().value;
    if (oldest) unwatchProjectAssets(oldest);
  }

  try {
    let watcher: ReturnType<typeof watch> | null = null;
    try {
      watcher = watch(assetsDir, { recursive: true }, (eventType, filename) => {
        if (!filename) return;
        // 11-H3: debounce. A single editor save fires 5-20 fs.watch
        // events; broadcasting on each one overwhelmed the studio
        // hook. Coalesce into one broadcast per ~100ms quiet window
        // per project. The debounce timer is also cleared in
        // unwatchProjectAssets() so we don't leak pending timers
        // when the project is torn down.
        const existing = assetWatcherDebounceTimers.get(projectId);
        if (existing) clearTimeout(existing);
        const timer = setTimeout(() => {
          assetWatcherDebounceTimers.delete(projectId);
          broadcastEvent({
            type: "asset:updated",
            asset: { id: `scan-${projectId}`, filename: String(filename) } as GameAsset,
            // 10-L5: tag the file-watcher event with the project so the
            // studio hook can ignore events for other projects' assets.
            projectId,
          } as WSEvent);
        }, ASSET_WATCHER_DEBOUNCE_MS);
        assetWatcherDebounceTimers.set(projectId, timer);
      });
    } catch (err) {
      // 10-H10: `fs.watch` with `recursive: true` is unsupported on Linux
      // (throws ENOSYS) and Android. On those platforms there's no
      // cheap way to watch a deep tree synchronously, so the watcher is
      // logged as unavailable and the UI falls back to its existing
      // polling refresh path (refetch on /api/assets every N seconds).
      const code = (err as NodeJS.ErrnoException)?.code;
      if (code === "ENOSYS" || code === "ERR_FEATURE_UNAVAILABLE_ON_PLATFORM") {
        logger.warn(
          { projectId, assetsDir, code },
          "fs.watch recursive unsupported on this platform — asset updates will rely on the UI's poll refresh",
        );
        return;
      }
      throw err;
    }

    assetWatchers.set(projectId, watcher);
    logger.info({ projectId, assetsDir }, "Started watching project assets");

    watcher.on("error", (err) => {
      logger.error({ projectId, err }, "Asset watcher error");
      unwatchProjectAssets(projectId);
    });
  } catch {
    // Watch may fail if directory doesn't exist yet
  }
}

export const assetsRouter: Router = Router();

// GET /api/assets?projectId=... - Scan workspace assets merged with metadata overlay
assetsRouter.get("/", async (req: Request, res: Response) => {
  const projectId = req.query.projectId as string | undefined;
  const config = loadConfig();
  const workspaceDir = path.resolve(config.WORKSPACE_DIR);

  try {
    let assetsDir: string;
    if (projectId) {
      const project = await getProjectById(projectId);
      assetsDir = resolveAssetsDir(workspaceDir, project?.workspacePath);
      // Start watching for real-time updates
      watchProjectAssets(projectId, assetsDir);
    } else {
      assetsDir = path.join(workspaceDir, "assets");
    }

    // Read metadata overlay from assets.json
    let overlayData: AssetsData;
    try {
      overlayData = await readData<AssetsData>("assets.json");
    } catch {
      overlayData = DEFAULT_ASSETS;
    }

    // Build overlay map keyed by relative path for O(1) lookup
    const overlayMap = new Map<string, Partial<GameAsset>>();
    for (const asset of overlayData.assets) {
      if (asset.path) overlayMap.set(asset.path, asset);
    }

    // Scan filesystem
    const scannedAssets = await scanAssetsDir(assetsDir, workspaceDir, overlayMap);

    // Build response: scanned assets + overlay-only assets (if any)
    const scannedPaths = new Set(scannedAssets.map((a) => a.path));
    const overlayOnly = overlayData.assets.filter((a) => a.path && !scannedPaths.has(a.path));

    const mergedAssets = [...scannedAssets, ...overlayOnly];

    // Deduplicate by id — prefer scanned assets over overlay entries
    const dedupedAssets: GameAsset[] = [];
    const seenIds = new Set<string>();
    for (const asset of mergedAssets) {
      if (!seenIds.has(asset.id)) {
        seenIds.add(asset.id);
        dedupedAssets.push(asset);
      }
    }

    res.json({
      success: true,
      data: {
        // 10-L1: include a signed thumbnail URL on every asset so the
        // frontend can render <img src=...> without re-deriving the
        // signature. The signature is `HMAC(API_SECRET, "thumbnail:" +
        // asset.id)` truncated to 32 hex chars — long enough to be
        // collision-resistant, short enough not to bloat the JSON.
        assets: dedupedAssets.map((a) => ({
          ...a,
          signedThumbnailUrl: a.thumbnailPath
            ? `/api/assets/${a.id}/thumbnail?sig=${signThumbnailId(a.id)}`
            : undefined,
        })),
        artBible: overlayData.artBible ?? DEFAULT_ASSETS.artBible,
      },
    });
  } catch (error) {
    logger.error({ error }, "Failed to scan assets");
    res.status(500).json({ success: false, error: "Failed to scan assets" });
  }
});

// GET /api/assets/:id - Get asset by ID
assetsRouter.get("/:id", async (req: Request, res: Response) => {
  const { id } = req.params;
  const projectId = req.query.projectId as string | undefined;
  const config = loadConfig();
  const workspaceDir = path.resolve(config.WORKSPACE_DIR);

  try {
    let assetsDir: string;
    if (projectId) {
      const project = await getProjectById(projectId);
      assetsDir = resolveAssetsDir(workspaceDir, project?.workspacePath);
    } else {
      assetsDir = path.join(workspaceDir, "assets");
    }

    // Read overlay
    let overlayData: AssetsData;
    try {
      overlayData = await readData<AssetsData>("assets.json");
    } catch {
      overlayData = DEFAULT_ASSETS;
    }

    const overlayMap = new Map<string, Partial<GameAsset>>();
    for (const asset of overlayData.assets) {
      if (asset.path) overlayMap.set(asset.path, asset);
    }

    const scanned = await scanAssetsDir(assetsDir, workspaceDir, overlayMap);
    const asset = scanned.find((a) => a.id === id) ?? overlayData.assets.find((a) => a.id === id);

    if (!asset) {
      res.status(404).json({ success: false, error: "Asset not found" });
      return;
    }
    res.json({ success: true, data: asset });
  } catch {
    res.status(500).json({ success: false, error: "Failed to read asset" });
  }
});

// GET /api/assets/:id/thumbnail - Serve thumbnail image file
assetsRouter.get("/:id/thumbnail", async (req: Request, res: Response) => {
  // Express 5 widens req.params values to `string | string[]` (it can't
  // statically prove a path segment is single-valued). The route's
  // path uses a single `:id` segment, so the value is always a string
  // — cast through the unknown boundary to recover the narrower type
  // for downstream HMAC comparison (10-L1).
  const id = String(req.params.id ?? "");
  // 10-L1: require a valid HMAC signature on every thumbnail request.
  // The list endpoint computes the signature and embeds it in the URL
  // as `?sig=...`; the <img> tag fires the request without auth
  // headers, but the signature travels as a query param. Reject
  // anything missing or wrong — see signThumbnailId above.
  // Note: Express types `req.query` as ParsedQs where every value is
  // `string | string[] | ParsedQs | ParsedQs[]`. Narrow to a single
  // string and reject anything else (defense against `?sig=a&sig=b`).
  const rawSig = req.query.sig;
  const sig: string = typeof rawSig === "string" && rawSig.length > 0 ? rawSig : "";
  if (!sig || !verifyThumbnailSignature(id, sig)) {
    res.status(403).send("Forbidden");
    return;
  }
  try {
    const data = await readData<AssetsData>("assets.json");
    const asset = data.assets.find((a) => a.id === id);
    if (!asset || !asset.thumbnailPath) {
      res.status(404).send("Not found");
      return;
    }

    const config = loadConfig();
    const workspaceDir = path.resolve(config.WORKSPACE_DIR);
    const thumbAbsPath = path.resolve(workspaceDir, asset.thumbnailPath);

    // Lstat first to reject symlinks outright. A thumbnail path that points
    // at a symlink can be used to read arbitrary files on disk: the
    // previous version did a `startsWith` check on the unresolved path,
    // which a symlink in workspaceDir pointing at /etc would defeat. We
    // also enforce the workspace boundary on the realpath (defense in
    // depth) so a symlink target outside the workspace is rejected even
    // if the symlink itself is inside.
    try {
      const lst = await fs.lstat(thumbAbsPath);
      if (lst.isSymbolicLink()) {
        res.status(403).send("Forbidden");
        return;
      }
      if (!lst.isFile()) {
        res.status(404).send("Not found");
        return;
      }
    } catch {
      res.status(404).send("Not found");
      return;
    }

    // Defense-in-depth: realpath the resolved path and confirm it stays
    // inside WORKSPACE_DIR. Should never trigger given the lstat check
    // above, but a future regression that re-enables symlinks would still
    // be caught here.
    let realThumb: string;
    try {
      realThumb = await fs.realpath(thumbAbsPath);
    } catch {
      res.status(404).send("Not found");
      return;
    }
    const realWorkspace = await fs.realpath(workspaceDir).catch(() => workspaceDir);
    const realWorkspacePrefix = realWorkspace.endsWith(path.sep) ? realWorkspace : realWorkspace + path.sep;
    if (!realThumb.startsWith(realWorkspacePrefix) && realThumb !== realWorkspace) {
      res.status(403).send("Forbidden");
      return;
    }

    res.setHeader("Content-Type", "image/png");
    res.setHeader("Cache-Control", "public, max-age=3600");
    const stream = (await import("node:fs")).createReadStream(thumbAbsPath);
    // Without this handler, a stream that errors mid-read (file deleted
    // between stat and pipe, EIO on a flaky disk, etc.) would silently drop
    // the connection. The client would see a truncated image with a 200 OK
    // and the error-handler middleware can't recover because headers are
    // already sent.
    stream.on("error", (err) => {
      // 12-H11: log the error before deciding how to respond. The
      // previous implementation dropped the error on the floor after
      // ending the response, which made mid-stream failures invisible
      // in production. Without the log, a flaky disk that drops 1% of
      // thumbnail requests would show up as "images not loading" with
      // no server-side trace.
      logger.warn(
        { assetId: id, thumbPath: thumbAbsPath, err: err instanceof Error ? err.message : String(err), event: "asset_thumbnail_stream_error" },
        "Thumbnail stream errored mid-read",
      );
      if (!res.headersSent) {
        res.status(500).send("Error");
        return;
      }
      // Headers already sent — best we can do is end the response so the
      // client doesn't see a half-loaded image and the socket is freed.
      try { res.end(); } catch { /* socket already gone */ }
    });
    // 12-H11: also handle client abort (browser cancel, network drop).
    // Without an 'aborted' listener, Node logs "Request aborted" but
    // the stream keeps running and the file descriptor stays open
    // until the stream naturally ends. On a slow disk with many
    // cancellations, this leaks FDs. Wire up abort detection.
    req.on("aborted", () => {
      stream.destroy();
    });
    res.on("close", () => {
      // 12-H11: client disconnected before stream completed. Destroy
      // the stream so the underlying FD is released immediately
      // rather than at the next read.
      if (!res.writableEnded) {
        stream.destroy();
      }
    });
    stream.pipe(res);
  } catch {
    res.status(500).send("Error");
  }
});

// POST /api/assets - Create new asset (metadata overlay only; file must exist on disk)
assetsRouter.post("/", async (req: Request, res: Response) => {
  const body = req.body as CreateAssetRequest;

  if (!body.filename || !body.type || !body.category) {
    res.status(400).json({
      success: false,
      error: "filename, type, and category are required",
    });
    return;
  }

  try {
    const now = new Date().toISOString();
    // Q5-6th: unguessable IDs. The previous `asset-${Date.now()}` was
    // predictable — combined with the unauthenticated /:id/thumbnail
    // endpoint (the only auth bypass in middleware/auth.ts), an attacker
    // could enumerate timestamps to discover existing assets. crypto
    // .randomUUID() is 122 bits of entropy, unguessable, and the
    // realpath boundary check already prevents arbitrary file reads.
    const newAsset: GameAsset = {
      id: `asset-${crypto.randomUUID()}`,
      filename: body.filename,
      type: body.type,
      category: body.category,
      sizeBytes: body.sizeBytes ?? 0,
      tags: body.tags ?? [],
      createdAt: now,
      updatedAt: now,
    };

    // Route the read-modify-write through updateData so the per-file mutex
    // serializes concurrent POST /api/assets calls. Without this, two
    // simultaneous creations can read the same array, both append, and the
    // second write clobbers the first (one asset disappears).
    const data = await updateData<AssetsData>("assets.json", (d) => {
      d.assets.push(newAsset);
      return d;
    });

    // 10-L5: include projectId on the event so subscribers (e.g. the
    // studio assets page) can filter out events for other projects
    // instead of triggering a wasteful refetch. Frontends read this
    // off the broadcast payload. The CreateAssetRequest type doesn't
    // carry projectId (the route doesn't require it), so we cast at
    // the boundary rather than widen the public type.
    broadcastEvent({
      type: "asset:created",
      asset: newAsset,
      projectId: (body as { projectId?: string }).projectId ?? null,
    } as WSEvent);

    res.status(201).json({ success: true, data: newAsset });
  } catch (error) {
    res.status(500).json({ success: false, error: "Failed to create asset" });
  }
});

// PATCH /api/assets/:id - Update asset metadata overlay
assetsRouter.patch("/:id", async (req: Request, res: Response) => {
  const { id } = req.params;
  const updates = req.body as UpdateAssetRequest;

  try {
    // Capture whether the asset existed before the lock so the response
    // matches the read-compute-write semantics. updateData's lock prevents
    // two concurrent PATCHes from clobbering each other.
    let isNew = false;
    let updatedAsset: GameAsset | null = null;

    await updateData<AssetsData>("assets.json", (d) => {
      const assetIndex = d.assets.findIndex((a) => a.id === id);
      if (assetIndex === -1) {
        const now = new Date().toISOString();
        const newAsset: GameAsset = {
          id: String(id),
          filename: updates.filename ?? "unknown",
          type: updates.type ?? "texture",
          category: updates.category ?? "prop",
          sizeBytes: updates.sizeBytes ?? 0,
          tags: updates.tags ?? [],
          createdAt: now,
          updatedAt: now,
          ...updates,
        };
        d.assets.push(newAsset);
        isNew = true;
        updatedAsset = newAsset;
        return d;
      }
      const assetId = String(id);
      const next: GameAsset = {
        ...d.assets[assetIndex],
        ...updates,
        id: assetId,
        updatedAt: new Date().toISOString(),
      };
      d.assets[assetIndex] = next;
      updatedAsset = next;
      return d;
    });

    if (!updatedAsset) {
      res.status(500).json({ success: false, error: "Failed to update asset" });
      return;
    }

    broadcastEvent({
      type: "asset:updated",
      asset: updatedAsset,
      // 10-L5: forward the request's projectId so the studio hook can
      // drop events for projects the current page isn't viewing.
      projectId: req.query.projectId as string | undefined ?? null,
    } as WSEvent);

    res.status(isNew ? 201 : 200).json({ success: true, data: updatedAsset });
  } catch (error) {
    res.status(500).json({ success: false, error: "Failed to update asset" });
  }
});

// DELETE /api/assets/:id - Delete asset
assetsRouter.delete("/:id", async (req: Request, res: Response) => {
  const { id } = req.params;

  try {
    // Snapshot the file-path-to-delete before mutating the list, then
    // perform the splice under updateData's lock so two concurrent
    // DELETEs on the same id can't double-unlink.
    let assetPath: string | null = null;
    let found = false;
    await updateData<AssetsData>("assets.json", (data) => {
      const assetIndex = data.assets.findIndex((a) => a.id === id);
      if (assetIndex === -1) return data;
      assetPath = data.assets[assetIndex].path ?? null;
      data.assets.splice(assetIndex, 1);
      found = true;
      return data;
    });

    if (!found) {
      res.status(404).json({ success: false, error: "Asset not found" });
      return;
    }

    // File deletion is best-effort; the metadata is already removed.
    if (assetPath) {
      try {
        const config = loadConfig();
        const workspaceDir = path.resolve(config.WORKSPACE_DIR);
        // 12-C7: validate assetPath before any path arithmetic. The stored
        // path could be absolute (path.join silently overrides on
        // absolute), could start with `..`, or could contain NUL bytes —
        // all of which let a manipulated asset record (e.g., set via a
        // future code path or imported from a manifest) escape the
        // workspace at delete time. Resolve and assert with path.relative
        // so the boundary check is symlink-aware and cross-platform.
        //
        // `assetPath` is captured by the updateData closure above, so
        // TS narrows it to `string` here but loses precision on some
        // control-flow paths. Hoist into a local const so narrowing is
        // unambiguous.
        const assetPathStr: string = assetPath;
        if (
          assetPathStr.length > 0 &&
          !assetPathStr.includes("\0") &&
          !path.isAbsolute(assetPathStr)
        ) {
          const filePath = path.resolve(workspaceDir, assetPath);
          const rel = path.relative(workspaceDir, filePath);
          // `rel` empty = filePath === workspaceDir (refuse).
          // `rel` starts with ".." or is absolute = escape (refuse).
          if (
            rel.length > 0 &&
            !rel.startsWith("..") &&
            !path.isAbsolute(rel) &&
            filePath !== workspaceDir
          ) {
            await fs.unlink(filePath);
          }
        }
      } catch {
        // File may not exist; continue
      }
    }

    broadcastEvent({
      type: "asset:deleted",
      assetId: id,
      // 10-L5: forward the projectId so the studio hook can filter.
      projectId: req.query.projectId as string | undefined ?? null,
    } as WSEvent);

    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ success: false, error: "Failed to delete asset" });
  }
});

// POST /api/assets/generate - Generate game asset via mflux pipeline
assetsRouter.post("/generate", async (req: Request, res: Response) => {
  const body = req.body as GenerateAssetRequest;
  const config = loadConfig();
  // 11-H4: resolve the asset-pipeline script directory relative to
  // THIS file's location instead of process.cwd(). The previous
  // `path.resolve(process.cwd(), "..", "..", "scripts", "...")`
  // assumed the server was started from apps/api/ — fine for `pnpm
  // dev`, but the production start (`pnpm start:api` inside the
  // container) runs from /app, breaking the path and the pipeline
  // silently fell through to "python: command not found".
  const here = fileURLToPath(import.meta.url);
  // this file is apps/api/src/routes/assets.ts; the script dir is
  // ../../../scripts/asset-pipeline from here.
  const scriptDir = path.resolve(path.dirname(here), "..", "..", "..", "scripts", "asset-pipeline");
  const projectDir = body.workspacePath
    ? resolveProjectWorkspace(body.workspacePath)
    : config.WORKSPACE_DIR;
  const projectAssetsDir = path.join(projectDir, "assets");

  // Ensure output directory exists
  await fs.mkdir(projectAssetsDir, { recursive: true });

  // Support batch mode via presets file
  if (body.presetsFile) {
    // Validate presetsFile is a bare filename within the script directory.
    // Then realpath the candidate so a symlink pointing outside scriptDir
    // is rejected — basename + access alone is bypassable.
    const presetsBasename = path.basename(body.presetsFile);
    const presetsPath = path.join(scriptDir, presetsBasename);
    if (presetsBasename !== body.presetsFile) {
      res.status(400).json({ success: false, error: `Invalid presets file: ${body.presetsFile}. Must be a filename in ${scriptDir}` });
      return;
    }
    let presetsReal: string;
    try {
      presetsReal = await fs.realpath(presetsPath);
    } catch {
      res.status(400).json({ success: false, error: `Invalid presets file: ${body.presetsFile}. Must be a filename in ${scriptDir}` });
      return;
    }
    const scriptReal = await fs.realpath(scriptDir);
    if (!presetsReal.startsWith(scriptReal + path.sep) && presetsReal !== scriptReal) {
      res.status(400).json({ success: false, error: `Presets file escapes script directory: ${body.presetsFile}` });
      return;
    }
    const args = [
      path.join(scriptDir, "asset-pipeline.py"),
      "--presets", presetsPath,
      "--output-dir", projectAssetsDir,
      "--workspace-dir", projectDir,
    ];

    try {
      const { stdout, stderr } = await execFileAsync(PYTHON_BIN, args, {
        cwd: scriptDir,
        timeout: 600_000,
        maxBuffer: SUBPROCESS_MAX_BUFFER,
      });

      const manifestPath = path.join(projectAssetsDir, "asset-manifest.json");
      let generated: GameAsset[] = [];
      let manifest: Record<string, unknown>[] = [];
      try {
        const raw = await fs.readFile(manifestPath, "utf-8");
        try {
          manifest = JSON.parse(raw);
        } catch (parseErr) {
          // Manifest is malformed — treat as empty rather than crashing the
          // whole generation request. The Python pipeline already wrote it,
          // so log the parse failure for diagnostics but continue.
          logger.error({ manifestPath, err: String(parseErr), event: "asset_manifest_parse_failed" },
            "Failed to parse asset manifest — treating as empty");
          manifest = [];
        }

        const data = await readData<AssetsData>("assets.json");
        const existingIds = new Set(data.assets.map((a) => a.id));

        for (const entry of manifest) {
          if (!existingIds.has(entry.id as string)) {
            const newAsset = manifestEntryToGameAsset(entry);
            data.assets.push(newAsset);
            generated.push(newAsset);
          }
        }

        if (generated.length > 0) {
          await writeData("assets.json", data);
          for (const asset of generated) {
            broadcastEvent({
              type: "asset:created",
              asset,
              // 10-L5: forward the projectId from the request body so
              // the studio hook can filter out events for other
              // projects. The /generate route receives projectId in
              // the body, not the query string.
              projectId: (body.workspacePath ? req.body?.projectId : null) ?? null,
            } as WSEvent);
          }
        }
      } catch {
        // manifest may not exist yet
      }

      res.json({
        success: true,
        data: { generated, log: stdout.slice(-2000) },
      });
    } catch (error: unknown) {
      const err = error as { stdout?: string; stderr?: string; message?: string };
      res.status(500).json({
        success: false,
        error: "Asset generation failed",
        details: err.stderr || err.message,
      });
    }
    return;
  }

  // Single asset generation
  if (!body.prompt || !body.name) {
    res.status(400).json({
      success: false,
      error: "prompt and name are required",
    });
    return;
  }

  // 12-C6: sanitize all CLI-bound strings. execFile does NOT shell-interpret
  // its args (no $(...), no `;`), but the Python pipeline parses them with
  // argparse — a tag like "--seed=99999" would be silently absorbed as a
  // flag override instead of a tag value. A name with embedded NUL or LF
  // could land in a manifest path or filename. Reject early so the failure
  // is a 400 instead of a confusing pipeline crash.
  const MAX_STR = 2000;
  const MAX_TAGS = 32;
  const isSafe = (s: unknown): s is string =>
    typeof s === "string" && s.length > 0 && s.length <= MAX_STR && !/[ -]/.test(s);
  // Names are also used as filenames — restrict to a conservative charset.
  if (!/^[A-Za-z0-9._\- ]{1,128}$/.test(body.name)) {
    res.status(400).json({
      success: false,
      error: "name must be alphanumeric with -, _, ., space (max 128 chars)",
    });
    return;
  }
  if (!isSafe(body.prompt)) {
    res.status(400).json({ success: false, error: "prompt is too long or contains control characters" });
    return;
  }
  if (body.negativePrompt !== undefined && !isSafe(body.negativePrompt)) {
    res.status(400).json({ success: false, error: "negativePrompt is invalid" });
    return;
  }
  if (body.model !== undefined && !/^[A-Za-z0-9._\-]{1,64}$/.test(String(body.model))) {
    res.status(400).json({ success: false, error: "model name is invalid" });
    return;
  }
  if (body.tags !== undefined) {
    if (!Array.isArray(body.tags) || body.tags.length > MAX_TAGS) {
      res.status(400).json({ success: false, error: `tags must be an array of <=${MAX_TAGS} strings` });
      return;
    }
    for (const t of body.tags) {
      // Reject `--...` flags AND control chars. Also cap individual tag length.
      if (typeof t !== "string" || t.length === 0 || t.length > 64 || t.startsWith("-") || /[ -]/.test(t)) {
        res.status(400).json({ success: false, error: "tags contain an invalid entry" });
        return;
      }
    }
  }

  const args = [
    path.join(scriptDir, "asset-pipeline.py"),
    "--prompt", body.prompt,
    "--name", body.name,
    "--type", body.type ?? "2d",
    "--category", body.category ?? "prop",
    "--width", String(Math.min(Math.max(Number(body.width) || 512, 64), 4096)),
    "--height", String(Math.min(Math.max(Number(body.height) || 512, 64), 4096)),
    "--steps", String(Math.min(Math.max(Number(body.steps) || 4, 1), 50)),
    "--output-dir", projectAssetsDir,
    "--workspace-dir", projectDir,
  ];

  if (body.seed !== undefined) args.push("--seed", String(body.seed));
  if (body.removeBg === false) args.push("--no-remove-bg");
  if (body.negativePrompt) args.push("--negative-prompt", body.negativePrompt);
  if (body.model) args.push("--model", body.model);
  if (body.gridSize) args.push("--grid-size", String(body.gridSize));
  if (body.spriteSheet) args.push("--sprite-sheet");
  if (body.spriteCols) args.push("--sprite-cols", String(body.spriteCols));
  if (body.spriteRows) args.push("--sprite-rows", String(body.spriteRows));
  if (body.tags?.length) args.push("--tags", ...body.tags);

  try {
    const { stdout } = await execFileAsync(PYTHON_BIN, args, {
      cwd: scriptDir,
      timeout: 600_000,
      maxBuffer: SUBPROCESS_MAX_BUFFER,
    });

    const manifestPath = path.join(projectAssetsDir, "asset-manifest.json");
    let generatedAsset: GameAsset | null = null;
    try {
      const raw = await fs.readFile(manifestPath, "utf-8");
      let manifest: Record<string, unknown>[] = [];
      try {
        manifest = JSON.parse(raw);
      } catch (parseErr) {
        logger.error({ manifestPath, err: String(parseErr), event: "asset_manifest_parse_failed_single" },
          "Failed to parse asset manifest (single mode) — no asset will be registered");
      }
      const last = manifest[manifest.length - 1];
      if (last) {
        const data = await readData<AssetsData>("assets.json");
        const existingIds = new Set(data.assets.map((a) => a.id));
        const assetId = last.id as string;
        if (!existingIds.has(assetId)) {
          const newAsset = manifestEntryToGameAsset(last);
          data.assets.push(newAsset);
          await writeData("assets.json", data);
          broadcastEvent({
            type: "asset:created",
            asset: newAsset,
          } as WSEvent);
          generatedAsset = newAsset;
        } else {
          generatedAsset = data.assets.find((a) => a.id === assetId) ?? null;
        }
      }
    } catch {
      // manifest may not exist yet
    }

    res.json({
      success: true,
      data: {
        asset: generatedAsset,
        log: stdout.slice(-1000),
      },
    });
  } catch (error: unknown) {
    const err = error as { stdout?: string; stderr?: string; message?: string };
    res.status(500).json({
      success: false,
      error: "Asset generation failed",
      details: err.stderr || err.message,
    });
  }
});

// GET /api/assets/generate/presets - List available preset files
assetsRouter.get("/generate/presets", async (_req: Request, res: Response) => {
  try {
    const scriptDir = path.resolve(process.cwd(), "..", "..", "scripts", "asset-pipeline");
    const files = await fs.readdir(scriptDir);
    const yamlFiles = files.filter(
      (f) => f.endsWith(".yaml") || f.endsWith(".yml")
    );
    res.json({ success: true, data: yamlFiles });
  } catch {
    res.json({ success: true, data: [] });
  }
});

// PATCH /api/assets/art-bible - Update art bible config
assetsRouter.patch("/art-bible", async (req: Request, res: Response) => {
  const updates = req.body as Partial<ArtBibleConfig>;

  try {
    // Read-modify-write under updateData's lock so concurrent PATCHes
    // don't lose updates to the art-bible object.
    let updatedArtBible: ArtBibleConfig | null = null;
    await updateData<AssetsData>("assets.json", (data) => {
      updatedArtBible = { ...data.artBible, ...updates };
      data.artBible = updatedArtBible;
      return data;
    });

    res.json({ success: true, data: { artBible: updatedArtBible ?? updates as ArtBibleConfig } });
  } catch (error) {
    res.status(500).json({ success: false, error: "Failed to update art bible" });
  }
});

// POST /api/assets/rescan - Force rescan for a project
assetsRouter.post("/rescan", async (req: Request, res: Response) => {
  const projectId = req.body.projectId as string | undefined;
  const config = loadConfig();
  const workspaceDir = path.resolve(config.WORKSPACE_DIR);

  try {
    let assetsDir: string;
    if (projectId) {
      const project = await getProjectById(projectId);
      assetsDir = resolveAssetsDir(workspaceDir, project?.workspacePath);
      watchProjectAssets(projectId, assetsDir);
    } else {
      assetsDir = path.join(workspaceDir, "assets");
    }

    let overlayData: AssetsData;
    try {
      overlayData = await readData<AssetsData>("assets.json");
    } catch {
      overlayData = DEFAULT_ASSETS;
    }

    const overlayMap = new Map<string, Partial<GameAsset>>();
    for (const asset of overlayData.assets) {
      if (asset.path) overlayMap.set(asset.path, asset);
    }

    const scannedAssets = await scanAssetsDir(assetsDir, workspaceDir, overlayMap);
    const scannedPaths = new Set(scannedAssets.map((a) => a.path));
    const overlayOnly = overlayData.assets.filter((a) => a.path && !scannedPaths.has(a.path));

    const mergedAssets = [...scannedAssets, ...overlayOnly];
    const dedupedAssets: GameAsset[] = [];
    const seenIds = new Set<string>();
    for (const asset of mergedAssets) {
      if (!seenIds.has(asset.id)) {
        seenIds.add(asset.id);
        dedupedAssets.push(asset);
      }
    }

    res.json({
      success: true,
      data: {
        assets: dedupedAssets,
        artBible: overlayData.artBible ?? DEFAULT_ASSETS.artBible,
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, error: "Failed to rescan assets" });
  }
});
